version: "3.0"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    environment:
      http.host: 0.0.0.0
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - elastic-net
    restart: unless-stopped
    ports:
      - 9200:9200
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - kibana-data:/usr/share/kibana/data
    networks:
      - elastic-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    restart: unless-stopped

networks:
  elastic-net:
    driver: bridge
    
volumes:
  es-data:
    driver: local
  kibana-data:
    driver: local